FROM node:20

WORKDIR /opt/next

ARG NEXT_PUBLIC_CLUB_NAME
ENV NEXT_PUBLIC_CLUB_NAME $NEXT_PUBLIC_CLUB_NAME
ARG NEXT_PUBLIC_HCAPTCHA_SITEKEY
ENV NEXT_PUBLIC_HCAPTCHA_SITEKEY $NEXT_PUBLIC_HCAPTCHA_SITEKEY

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

USER node
EXPOSE 3000
CMD ["npm", "start"]
