blockExoticSubdeps: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - webpack
  - react
  - react-dom
  - next
  - "@next/*"
  # Renovate security update: sharp@0.35.0
  - sharp@0.35.0
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160
allowBuilds:
  esbuild: set this to true or false
  msw: true
  sharp: true
  unrs-resolver: set this to true or false
