blockExoticSubdeps: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - webpack
  - react
  - react-dom
  - next
  - "@next/*"
  # Renovate security update: postcss@8.5.23
  - postcss@8.5.23
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160
allowBuilds:
  esbuild: set this to true or false
  msw: true
  sharp: true
  unrs-resolver: set this to true or false
